% This file defines the flow pattern which the pitch-plunge system will be
% subjected to.

% First we define the default flow velocity.
U0 = 10;

% Then we define the flow disturbance parameters. These are to set up a gust-like disturbance in the flow. They will eventually be applied in the applySettings file.
numDisturbancePoints = T/dt+1; % How many data points do we use for the disturbance? [-]
disturbanceMagnitude = 0; % The magnitude of the disturbance. [m/s]
disturbanceCenter = T/3; % The center of the disturbance. [s]
disturbanceRadius = 2; % The (time-wise) size of the disturbance. [s]
disturbanceTime = linspace(0,T,numDisturbancePoints);

% Next to that, we may also add some turbulence, generated by a Simulink block according to the Von Karman spectrum.
turbulenceFactor = 0; % This is the turbulence factor, with which we multiply the generated spectrum. Indicate 1 for a default (pretty strong) spectrum, 0 for no turbulence, or any other factor as desired.
turbulenceSeed = ceil(rand(1,4)*100000); % This is a seed for the turbulence. If you want to have the same turbulence every simulation run, insert a fixed number.
initialTurbulence = zeros(3,1); % This is the initial turbulence present in the system. When we are continuing with a previous simulation, and also want to continue with the turbulence given there, without getting discontinuities in the wind speed, we can set that through this parameter.